//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string price { get; set; }
        public string date { get; set; }
        public string type { get; set; }
        public int PersonId { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Person Person { get; set; }
    }
}
